add 墨奇音形
ayaka14732/awesome-rime pull request #41
Opened 2024-05-21 15:05 UTC by gaboolic

墨奇音形，支持自然码、小鹤、搜狗、微软双拼。墨奇音形是一个基于字形描述信息、递归拆分，最后取首末双形音托的码表开源的方案。详见墨奇码拆分规则。墨奇码的拆分码表已开源，目前已经拆分完成全部的通用规范汉字、常用繁体字，总计支持4万字。墨奇音形的方案支持ctrl+p开关显示墨奇辅助码+首末字形，ctrl+l开关显示墨奇拆字的拆分。

2024-05-22 17:46 UTC, ayaka14732 requested changes
文件太多了，应该属于「配置」，所以应该放在下面的「配置」这一节

2024-05-23 05:05 UTC, gaboolic commented
形碼・音形和“配置”是怎么分的，仅仅看文件数量吗？

https://github.com/bigshans/rime-zrm
https://github.com/ywxt/rime-huma
https://github.com/whjiang/zzdyx_rime
自然码＋辅码，虎碼輸入方案 哲豆音形，这些都在"形碼・音形"一栏，我不认为我的方案和以上几个方案有本质区别，
文件多 是因为加了几个反查的方案

2024-05-27 09:32 UTC, gaboolic commented
再比如星空键道的配置文件也很多， 不也放到音形？
https://github.com/xkinput/Rime_JD/tree/master/rime

2024-06-04 10:58 UTC, ayaka14732 commented
我之前说错了，的确不仅仅看文件数量。

rime 方案的 repo 的初衷是让用户（或未来的包管理器）可以直接通过下载 repo 中的文件的方式将方案加入到 rime 中。如果加入了反查的方案，就和那个方案本来的 repo 里的内容相冲突了。

星空键道文件也很多，但是都是属于星空键道这个 repo 里的内容，不包含其他方案的内容，这些文件都属于星空键道方案本身，所以属于方案。

如果加入了其他方案，就属于配置。

或者 repo 去除其他方案，然后在 README 中提示需要下载其他方案才可以反查，这样 repo 就属于方案了。

2024-06-04 11:02 UTC, ayaka14732 commented
其实星空键道那个 repo 应该将方案的文件放在 repo 根目录，才比较符合 rime 方案的习惯（我不是星空键道开发者，没有发言权）

2024-06-04 12:04 UTC, gaboolic commented
ok  其他方案确实包含的schema文件很少
后续我看看单独搞出来一个纯净版的 放到“音形”一栏

2024-06-04 13:15 UTC, ayaka14732 approved these changes

2024-06-04 13:15 UTC, merged